#include "supplements.h"

#include <mcp23x08.h>



void supplement_mcp23x17reg(py::module_ &subm)
{
  // MCP23x17 Registers
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IODIRA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IPOLA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", GPINTENA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", DEFVALA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", INTCONA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", GPPUA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", INTFA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", INTCAPA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", GPIOA);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", OLATA);
  
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IODIRB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IPOLB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", GPINTENB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", DEFVALB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", INTCONB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCONB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", GPPUB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", INTFB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", INTCAPB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", GPIOB);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", OLATB);

  // Bits in the IOCON register
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_UNUSED);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_INTPOL);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_ODR);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_HAEN);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_DISSLW);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_SEQOP);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_MIRROR);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_BANK_MODE);

  // Default initialisation mode
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", IOCON_INIT);

  // SPI Command codes
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", CMD_WRITE);
  ADD_RENAME_MODULE_ATTR(subm, "MCP23x17", CMD_READ);

}